[build]
builder = "NIXPACKS"
buildCommand = "cd resume_backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd resume_backend && python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
